### ISSUE TITLE
Setup GitHub repo gatsby-theme-pitayan

### ISSUE THREAD

**Issue by daiyanze** [Pitayan/gatsby-theme-pitayan#1]
This is a Gatsby plugin repo. Pitayan-base will be developed as a package including the preset configuration for a Gatsby blog and also a collection of UI components.

### Tasks
- [x] Apply gatsby-starter-blog to repo
- [x] Add gatsby plugins that doesn't come with the starter
    - [x] gatsby-plugin-sitemap
    - [x] gatsby-plugin-mdx
    - [x] gatsby-plugin-page-creator
    - [x] gatsby-plugin-catch-links
    - [x] gatsby-plugin-postcss
- [x] Add Tailwind and related libs
    - [x] gatsby-plugin-postcss 
    - [x] tailwindcss
    - [x] postcss
    - [x] autoprefixer
    - [x] eslint-plugin-import
    - [x] gatsby-plugin-eslint
- [x] Setup gatsby-config.js
- [x] Remove default template source from `src/`
