### ISSUE TITLE
Create Style Guide page for gatsby-plugin-pitayan

### ISSUE THREAD

**Issue by daiyanze** [Pitayan/gatsby-theme-pitayan#3]
### Tasks
- [x] Create "style guide" page
    - [x] Typography
        - [x] Fonts
        - [x] Headings
        - [x] Paragraph
        - [x] Semantic Elements
        - [x] Quotes
        - [x] Address
        - [x] Code
    - [x] Colors
    - [x] Elements
        - [x] Button
        - [x] Divider
        - [x] Link
        - [x] Input
    - [x] Components
        - [x] Pagination
        - [x] Subscription
        - [x] Selection popup: select text for sharing
        - [x] Article Panel
- [x] Tune up "Dark mode"

**Comment by daiyanze** [comment]
Migrate from gatsby-transformer-remark to gatsby-plugin-mdx in order to use React components in markdown files.
https://www.gatsbyjs.com/docs/how-to/routing/migrate-remark-to-mdx/

**Comment by daiyanze** [comment]
Default Light Theme

![localhost_8000_s (1)](https://user-images.githubusercontent.com/14920529/136310267-84f03fa5-f81c-4504-ad24-5cd8304cda3a.png)

**Comment by daiyanze** [comment]
Todos:
- Need some adjustment on the page content

**Comment by daiyanze** [comment]
Done style guide page creation
